### ISSUE TITLE
Mojibake

### ISSUE THREAD

**Issue by Mederic64** [Sazaju/VH-Translation-Editor#32]
Untranslated text appears in mojibake, as well as translated text, in japanese locale or american locale.

![mojibake](https://cloud.githubusercontent.com/assets/7494170/9424135/114f3680-48e1-11e5-9dd3-db529ecfa26e.png)
![mynockscreen](https://cloud.githubusercontent.com/assets/7494170/9424136/11532a56-48e1-11e5-9491-ad06b80f9b41.png)

**Comment by Sazaju** [comment]
Uh, strange. I will check that as soon as I go back on Linux.

**Comment by Sazaju** [comment]
It's specific to Windows. I am on Kubuntu which uses UTF-8, so I don't have the problem there. On Windows it is different, so it may mess up everything. I have forced it to UTF-8 and now it seems to work. I'll provide the new JAR and if it is OK for you you can close this issue.
