### ISSUE TITLE
Statistics

### ISSUE THREAD

**Issue by Mederic64** [Sazaju/VH-Translation-Editor#33]
Somewhere in the program is displayed number of lines and percentage of left translated/untranslated in all displayed maps.

**Comment by Sazaju** [comment]
I may add the root node of the list (there is one already, it is just hidden) and compute the progress based on the child nodes. This should be easy, but it would limit to the same summary than for each map (% done + entries remaining). I don't know for instance if other global statistics would be useful. But we could see that when we have such extended features for individual maps.

**Comment by Sazaju** [comment]
I have added [the project node](https://github.com/matthieu-vergne/Translation/commit/a4cf3febebdc31955c00f1c07a81f7cd2df7df6b) with real-time update (when maps are loaded + after the saving of each map). It should be there for the next version. I hope you will like it.
![screen4](https://cloud.githubusercontent.com/assets/469340/9534719/035348b2-4d1b-11e5-9492-177e002cb36d.png)
