### ISSUE TITLE
Style guide

### ISSUE THREAD

**Issue by Mederic64** [Sazaju/VH-Translation-Editor#34]
A distinctive graphical marker notices the user that a map contains determined characters that are not valid with the style recommendations in the assembla wiki.

An option allows to automatically fix separate or all problematic entries.

See https://www.assembla.com/spaces/VH/wiki/Style_Guide for more info.

**Comment by Sazaju** [comment]
I mark it as a duplicate of issue #4. If you think that it should be completed with new ideas, just add them in that issue.
